feat(workspace): implemented resync from s3 to runner workspace

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -83,3 +83,32 @@ jobs:
             terraform -v
             echo "Hello World. I am ${{github.repository}}"
             echo "Testing $GITHUB_REPOSITORY variable"
+  test-workspace-sync: 
+    runs-on: ubuntu-latest
+    if: github.repository_owner == 'sonikro'
+    permissions:
+      contents: read
+      id-token: write
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: ./
+        with:
+          role_arn: "${{secrets.TEST_ROLE_ARN}}"
+          image: alpine
+          region: us-east-1
+          vpc_id: "${{secrets.TEST_VPC_ID}}"
+          shell: sh
+          run: |
+            ls -la
+            echo "ecs generated contend" > testfile.txt
+
+      - shell: bash
+        run: |
+          if [ -f "testfile.txt" ]; 
+          then
+            cat testfile.txt
+          else
+            echo "testfile is missing"
+            exit 1
+          fi
